package net.hypnoz.msadmin.enumeration;

public enum ProfessionEnum {
    ACHETEUR("Acheteur"),
    ACHETEUR_DESPACES_PUB("Acheteur d'espaces pub"),
    ACHETEUR_INFORMATIQUE_ET_TLCOM("Acheteur Informatique Et Télécom"),
    ACTUAIRE("Actuaire"),
    ADJOINT_ADMINISTRATIF("Adjoint administratif"),
    ADJOINT_ADMINISTRATIF_DADMINISTRATION_CENTRALE("Adjoint administratif d'administration centrale"),
    ADJOINT_ADMINISTRATIF_TERRITORIAL("Adjoint administratif territorial"),
    ADJOINT_TECHNIQUE_DE_RECHERCHE_ET_DE_FORMATION("Adjoint technique de recherche et de formation"),
    ADJOINT_TERRITORIAL_DANIMATION("Adjoint territorial d'animation"),
    ADMINISTRATEUR_BASE_DE_DONNES("Administrateur base de données"),
    ADMINISTRATEUR_DE_BASES_DE_DONNES("Administrateur De Bases De Données"),
    ADMINISTRATEUR_DE_BIENS("Administrateur de biens"),
    ADMINISTRATEUR_DE_RSEAU("Administrateur De Réseau"),
    ADMINISTRATEUR_JUDICIAIRE("Administrateur judiciaire"),
    AFFRTEUR("Affréteur"),
    AGENT_ADMINISTRATIF_ET_AGENT_DES_SERVICES_TECHNIQUES("Agent administratif et agent des services techniques"),
    AGENT_DENTRETIEN_DASCENSEURS("Agent d'entretien d'ascenseurs"),
    AGENT_DEXPLOITATION_DES_QUIPEMENTS_AUDIOVISUELS("Agent d'exploitation des équipements audiovisuels"),
    AGENT_DE_MAINTENANCE_EN_MCANIQUE("Agent de maintenance en mécanique"),
    AGENT_DE_MATRISE("Agent de maîtrise"),
    AGENT_DE_POLICE_MUNICIPALE("Agent de police municipale"),
    AGENT_DE_RSERVATION("Agent de réservation"),
    AGENT_DES_SERVICES_TECHNIQUES_DADMINISTRATION_CENTRALE("Agent des services techniques d'administration centrale"),
    AGENT_DES_SERVICES_TECHNIQUES_DE_PRFECTURE("Agent des services techniques de préfecture"),
    AGENT_DES_SYSTMES_DINFORMATION_ET_DE_COMMUNICATION("Agent des systèmes d'information et de communication"),
    AGENT_IMMOBILIER("Agent immobilier"),
    AGENT_SPCIALIS_DE_POLICE_TECHNIQUE_ET_SCIENTIFIQUE("Agent spécialisé de police technique et scientifique"),
    AGENT_TECHNIQUE_DE_RECHERCHE_ET_DE_FORMATION("Agent technique de recherche et de formation"),
    AIDE_COMPTABLE("Aide comptable"),
    AIDE_DE_LABORATOIRE("Aide de laboratoire"),
    AIDE_MDICOPSYCHOLOGIQUE("Aide médico-psychologique"),
    AIDE_SOIGNANT("Aide soignant"),
    AIDE_TECHNIQUE_DE_LABORATOIRE("Aide technique de laboratoire"),
    AMBULANCIER("Ambulancier"),
    ANALYSTE_DEXPLOITATION("Analyste D'Exploitation"),
    ANALYSTE_FINANCIER("Analyste financier"),
    ANALYSTE_PROGRAMMEUR("Analyste programmeur"),
    ANIMATEUR("Animateur"),
    ANIMATEUR_DE_CLUB_DE_VACANCES("Animateur de club de vacances"),
    ANIMATEUR_DE_FORMATION("Animateur de formation"),
    ANIMATEUR_ENVIRONNEMENT("animateur environnement"),
    ANIMATEUR_SOCIOCULTUREL("Animateur socioculturel"),
    ANTIQUAIRE("Antiquaire"),
    ARCHOLOGUE("Archéologue"),
    ARCHITECTE("Architecte"),
    ARCHITECTE_DINTRIEUR("Architecte d'intérieur"),
    ARCHITECTE_DE_BASES_DE_DONNES("Architecte De Bases De Données"),
    ARCHITECTE_DE_RSEAU("Architecte De Réseau"),
    ARCHITECTE_DE_SYSTME_DINFORMATION("Architecte De Système D'Information"),
    ARCHITECTE_MATRIEL("Architecte Matériel"),
    ARCHIVISTE("Archiviste"),
    ARTISTEPEINTRE("Artiste-peintre"),
    ASSISTANT_DE_CONSERVATION("Assistant de conservation"),
    ASSISTANT_DE_JUSTICE("Assistant de justice"),
    ASSISTANT_DE_RESSOURCES_HUMAINES("Assistant de ressources humaines"),
    ASSISTANT_DE_SERVICE_SOCIAL("Assistant de service social"),
    ASSISTANT_DES_BIBLIOTHQUES("Assistant des bibliothèques"),
    ASSISTANT_INGNIEUR("Assistant ingénieur"),
    ASSISTANT_MDICOTECHNIQUE("Assistant médico-technique"),
    ASSISTANT_SOCIODUCATIF("Assistant socio-éducatif"),
    ASSISTANT_SON("Assistant son"),
    ASSISTANT_VTRINAIRE("Assistant vétérinaire"),
    ASSISTANTE_DE_GESTION_PMIPME("Assistante de gestion PMI/PME"),
    ASSISTANTE_MATERNELLE("Assistante maternelle"),
    ASSISTANTE_SOCIALE("Assistante sociale"),
    ASTRONOME("Astronome"),
    ATTACH_DADMINISTRATION_ET_DINTENDANCE("Attaché d'administration et d'intendance"),
    ATTACH_DADMINISTRATION_HOSPITALIRE("Attaché d'administration hospitalière"),
    ATTACH_DADMINISTRATION_CENTRALE("Attaché d'administration centrale"),
    ATTACH_DADMINISTRATION_SCOLAIRE_ET_UNIVERSITAIRE("Attaché d'administration scolaire et universitaire"),
    ATTACH_DE_CONSERVATEUR_DE_PATRIMOINE("Attaché de conservateur de patrimoine"),
    ATTACH_DE_POLICE("Attaché de police"),
    ATTACH_DE_PRFECTURE("Attaché de préfecture"),
    ATTACH_DE_PRESSE("Attaché de presse"),
    AUDITEUR_INFORMATIQUE("Auditeur Informatique"),
    AUTEURSCNARISTE_MULTIMDIA("Auteur-scénariste multimédia"),
    AUXILIAIRE_DE_PURICULTURE("Auxiliaire de puériculture"),
    AUXILIAIRE_DE_VIE_SOCIALE("Auxiliaire de vie sociale"),
    AUXILLIAIRE_DE_VIE("Auxilliaire de vie"),
    AVOCAT("Avocat"),
    BARMAN("Barman"),
    BIBLIOTHCAIRE("Bibliothécaire"),
    BIBLIOTHCAIRE_ADJOINT_SPCIALIS("Bibliothécaire adjoint spécialisé"),
    BIJOUTIER_JOAILLIER("Bijoutier joaillier"),
    BILLETTISTE("Billettiste"),
    BIOINFORMATICIEN("Bio-informaticien"),
    BIOLOGISTE("Biologiste"),
    BOBINIER_DE_LA_CONSTRUCTION_LECTRIQUE("Bobinier de la construction électrique"),
    BOUCHER("Boucher"),
    BOULANGER("Boulanger"),
    BRASSEUR_MALTEUR("Brasseur malteur"),
    BRONZIER("Bronzier"),
    BCHERON("Bûcheron"),
    CADREUR("Cadreur"),
    CAPITAINE_DE_SAPEURPOMPIER("Capitaine de Sapeur-Pompier"),
    CARRELEUR("Carreleur"),
    CARROSSIER_RPARATEUR("Carrossier réparateur"),
    CAVISTE("Caviste"),
    CHARCUTIERTRAITEUR("Charcutier-traiteur"),
    CHARG_DE_CLIENTLE("Chargé de clientèle"),
    CHARG_DE_RFRENCEMENT("Chargé De Référencement"),
    CHARG_DE_RELATIONS_PUBLIQUES("Chargé de relations publiques"),
    CHARPENTIER("Charpentier"),
    CHAUDRONNIER("Chaudronnier"),
    CHEF_DATELIER_DES_INDUSTRIES_GRAPHIQUES("Chef d'atelier des industries graphiques"),
    CHEF_DE_CHANTIER("Chef de chantier"),
    CHEF_DE_COMPTOIR("Chef de comptoir"),
    CHEF_DE_FABRICATION("Chef de fabrication"),
    CHEF_DE_PRODUITS_VOYAGES("Chef de produits voyages"),
    CHEF_DE_PROJET_PROJECT_MANAGER("Chef De Projet - Project Manager"),
    CHEF_DE_PROJET_INFORMATIQUE("Chef de projet informatique"),
    CHEF_DE_PROJET_MULTIMEDIA("Chef de projet multimedia"),
    CHEF_DE_PUBLICIT("Chef de publicité"),
    CHEF_DE_RAYON("Chef de rayon"),
    CHEF_DE_SERVICE_DE_POLICE_MUNICIPALE("Chef de service de Police municipale"),
    CHEF_OPRATEUR("Chef opérateur"),
    CHERCHEUR("Chercheur"),
    CHERCHEUR_EN_INFORMATIQUE("Chercheur En Informatique"),
    CHIRURGIENDENTISTE("Chirurgien-dentiste"),
    CHOCOLATIER_CONFISEUR("Chocolatier confiseur"),
    CLERC_DE_NOTAIRE("Clerc de notaire"),
    COIFFEUR("Coiffeur"),
    COMDIEN("Comédien"),
    COMMIS_DE_CUISINE("Commis de cuisine"),
    COMMISSAIRE_DE_POLICE("Commissaire de police"),
    COMMISSAIRE_PRISEUR("Commissaire priseur"),
    COMPORTEMENTALISTE("comportementaliste"),
    COMPTABLE("Comptable"),
    CONCEPTEUR_DE_JEUX_LECTRONIQUES("Concepteur De Jeux Électroniques"),
    CONCEPTEUR_RDACTEUR("Concepteur rédacteur"),
    CONCIERGE_DHTEL("Concierge d'hôtel"),
    CONDUCTEUR("Conducteur"),
    CONDUCTEUR_DAPPAREILS("Conducteur d'appareils"),
    CONDUCTEUR_DAUTOBUS("Conducteur d'autobus"),
    CONDUCTEUR_DAUTOMOBILE("Conducteur d'automobile"),
    CONDUCTEUR_DENGINS_EN_BTP("Conducteur d'engins en BTP"),
    CONDUCTEUR_DE_MACHINE_IMPRIMER_DEXPLOITATION_COMPLEXE("Conducteur de machine à imprimer d'exploitation complexe"),
    CONDUCTEUR_DE_MACHINE_IMPRIMER_SIMPLE("Conducteur de machine à imprimer simple"),
    CONDUCTEUR_DE_MACHINES("Conducteur de machines"),
    CONDUCTEUR_DE_MACHINES_AGRO("Conducteur de machines agro"),
    CONDUCTEUR_DE_STATION_DPURATION("Conducteur de station d'épuration"),
    CONDUCTEUR_DE_TAXI("Conducteur de taxi"),
    CONDUCTEUR_DE_TRAIN("conducteur de train"),
    CONDUCTEUR_DE_TRAVAUX("Conducteur de travaux"),
    CONDUCTEUR_ROUTIER("Conducteur routier"),
    CONSEIL_EN_ASSISTANCE_MAITRISE_DOUVRAGE("Conseil En Assistance À Maitrise D'Ouvrage"),
    CONSEILLER_DINSERTION_ET_DE_PROBATION("Conseiller d'insertion et de probation"),
    CONSEILLER_DORIENTATION("Conseiller d'orientation"),
    CONSEILLER_DORIENTATIONPSYCHOLOGUE("Conseiller d'orientation-psychologue"),
    CONSEILLER_EN_DVELOPPEMENT_TOURISTIQUE("Conseiller en développement touristique"),
    CONSEILLER_EN_CONOMIE_SOCIALE_ET_FAMILIALE("Conseiller en économie sociale et familiale"),
    CONSEILLER_SOCIODUCATIF("Conseiller socio-éducatif"),
    CONSEILLER_TERRITORIAL_DES_ACTIVITS_PHYSIQUES_ET_SPORTIVES("Conseiller territorial des activités physiques et sportives"),
    CONSEILLERS_PRINCIPAUX_DDUCATION("Conseillers principaux d'éducation"),
    CONSERVATEUR_DE_BIBLIOTHQUE("Conservateur de bibliothèque"),
    CONSERVATEUR_DU_PATRIMOINE("Conservateur du patrimoine"),
    CONSULTANT_COMMUNICATION_RSEAUX("Consultant Communication & Réseaux"),
    CONSULTANT_EBUSINESS("Consultant E-Business"),
    CONSULTANT_EN_CONDUITE_DU_CHANGEMENT("Consultant En Conduite Du Changement"),
    CONSULTANT_EN_ELEARNING("Consultant En E-Learning"),
    CONSULTANT_EN_GESTION_DE_LA_RELATION_CLIENT("Consultant En Gestion De La Relation Client"),
    CONSULTANT_EN_ORGANISATION_DES_SYSTMES_DINFORMATION("Consultant En Organisation Des Systèmes D'Information"),
    CONSULTANT_EN_TECHNOLOGIES("Consultant En Technologies"),
    CONSULTANT_ERP("Consultant Erp"),
    CONSULTANT_FONCTIONNEL("Consultant Fonctionnel"),
    CONSULTANT_INFORMATIQUE("Consultant Informatique"),
    CONTRLEUR_ARIEN("Contrôleur aérien"),
    CONTRLEUR_DE_GESTION("Contrôleur de gestion"),
    CONTRLEUR_DE_TRAVAUX("Contrôleur de travaux"),
    CONTRLEUR_DES_SERVICES_TECHNIQUES_DU_MATRIEL("Contrôleur des services techniques du matériel"),
    CONTRLEUR_DES_SYSTMES_DINFORMATION_ET_DE_COMMUNICATION("Contrôleur des systèmes d'information et de communication"),
    CONTRLEUR_DU_TRAVAIL("Contrôleur du travail"),
    CONTRLEUR_EN_LECTRICIT_ET_LECTRONIQUE("Contrôleur en électricité et électronique"),
    CONVOYEUR_DE_FONDS("Convoyeur de fonds"),
    COORDINATRICE_DE_CRCHES("Coordinatrice de crèches"),
    CORRECTEUR("Correcteur"),
    COSTUMIERHABILLEUR("Costumier-habilleur"),
    COURTIER_DASSURANCES("Courtier d'assurances"),
    COUVREUR("Couvreur"),
    CRATEUR_DE_PARFUM("Créateur de parfum"),
    CUISINIER("Cuisinier"),
    CYBERDOCUMENTALISTE("Cyberdocumentaliste"),
    DANSEUR("Danseur"),
    DCORATEURSCNOGRAPHE("Décorateur-scénographe"),
    DLGU_MDICAL("Délégué médical"),
    DMNAGEUR("Déménageur"),
    DMOGRAPHE("Démographe"),
    DPANNEUR_TV_LECTROMNAGER("Dépanneur tv électroménager"),
    DESIGNER_AUTOMOBILE("Designer automobile"),
    DESSINATEUR_DE_PRESSE("Dessinateur de presse"),
    DESSINATEUR_INDUSTRIEL("Dessinateur industriel"),
    DTECTIVE_PRIV("Détective privé"),
    DVELOPPEUR("Développeur"),
    DITTICIEN("Diététicien"),
    DIRECTEUR_ARTISTIQUE("Directeur artistique"),
    DIRECTEUR_COMMERCIAL("Directeur Commercial"),
    DIRECTEUR_DTABLISSEMENT_SOCIAL_ET_MDICOSOCIAL("Directeur d?établissement social et médico-social"),
    DIRECTEUR_DHPITAL("Directeur d?hôpital"),
    DIRECTEUR_DTABLISSEMENT_DENSEIGNEMENT_ARTISTIQUE("Directeur d'établissement d'enseignement artistique"),
    DIRECTEUR_DTABLISSEMENT_SANITAIRE_ET_SOCIAL("Directeur d'établissement sanitaire et social"),
    DIRECTEUR_DOFFICE_DE_TOURISME("Directeur d'office de tourisme"),
    DIRECTEUR_DE_COLLECTION("Directeur de collection"),
    DIRECTEUR_DE_PARC_NATUREL("Directeur de parc naturel"),
    DIRECTEUR_DE_PROJET("Directeur De Projet"),
    DIRECTEUR_DE_RESSOURCES_HUMAINES("Directeur de ressources humaines"),
    DIRECTEUR_DES_SOINS("Directeur des soins"),
    DIRECTEUR_DES_SYSTMES_DINFORMATION("Directeur Des Systèmes D'Information"),
    DIRECTEUR_TECHNIQUE("Directeur Technique"),
    DOCKER("Docker"),
    DOCUMENTALISTE("Documentaliste"),
    DOUANIER("Douanier"),
    EBNISTE("Ebéniste"),
    EBOUEUR("Eboueur"),
    ECOCONSEILLER("Eco-conseiller"),
    ECOTOXICOLOGUE("Ecotoxicologue"),
    EDUCATEUR_DE_JEUNES_ENFANTS("Educateur de jeunes enfants"),
    EDUCATEUR_SPCIALIS("Educateur spécialisé"),
    EDUCATEUR_SPORTIF("Educateur sportif"),
    EDUCATEUR_TECHNIQUE_SPCIALIS("Educateur technique spécialisé"),
    EDUCATEUR_TERRITORIAL_DES_ACTIVITS_PHYSIQUES_ET_SPORTIVES("Educateur territorial des activités physiques et sportives"),
    ELECTRICIEN_DE_MAINTENANCE("Electricien de maintenance"),
    ELECTRICIEN_DU_BTIMENT("Electricien du bâtiment"),
    ELECTRICIEN_LECTRONICIEN_AUTO("Electricien électronicien auto"),
    EMPLOY_DE_GROUPAGE("Employé de groupage"),
    EMPLOY_DE_RESTAURATION_RAPIDE("Employé de restauration rapide"),
    EMPLOYS_DU_HALL_DES_HTELS("Employés du hall des hôtels"),
    ENCADREUR("Encadreur"),
    ENSEIGNANT_CHERCHEUR("Enseignant Chercheur"),
    ENTRANEUR_SPORTIF("Entraîneur sportif"),
    ERGONOME("Ergonome"),
    ERGOTHRAPEUTE("Ergothérapeute"),
    ESTHTICIENNECOSMTICIENNE("Esthéticienne-cosméticienne"),
    ETALAGISTE_DCORATEUR("Etalagiste décorateur"),
    ETHNOLOGUE("Ethnologue"),
    EXPERT_AUTOMOBILE("Expert automobile"),
    EXPERT_COMPTABLE("Expert comptable"),
    EXPERT_EN_SCURIT_INFORMATIQUE("Expert En Sécurité Informatique"),
    FACTEUR_INSTRUMENTAL("Facteur instrumental"),
    FEMME_DE_CHAMBRE_OU_VALET_DE_CHAMBRE("Femme de chambre ou valet de chambre"),
    FLEURISTE("Fleuriste"),
    FORFAITISTE("Forfaitiste"),
    FORMATEUR_EN_INFORMATIQUE("Formateur En Informatique"),
    GAME_DESIGNER("Game designer"),
    GARON_DE_CAF("Garçon de café"),
    GARDE_DU_CORPS("Garde du corps"),
    GARDECHAMPTRE("Garde-champêtre"),
    GARDIEN_DIMMEUBLE("Gardien d'immeuble"),
    GARDIEN_DE_LA_PAIX("Gardien de la paix"),
    GENDARME("Gendarme"),
    GOGRAPHE("Géographe"),
    GOLOGUE("Géologue"),
    GOMTRE_TOPOGRAPHE("Géomètre topographe"),
    GRANT_DHTEL("Gérant d'hôtel"),
    GESTIONNAIRE_DE_PARC_MICROINFORMATIQUE("Gestionnaire De Parc Micro-Informatique"),
    GRAPHISTE_MULTIMDIA("Graphiste multimédia"),
    GREFFIER("Greffier"),
    GUICHETETIER("Guichetetier"),
    GUIDE_ACCOMPAGNATEUR("Guide accompagnateur"),
    GUIDE_DE_HAUTE_MONTAGNE("Guide de haute montagne"),
    GUIDE_INTERPRTE("Guide Interprète"),
    HORICULTEUR("Horiculteur"),
    HOTLINER_TECHNICIEN_HELPDESK("Hot-Liner Technicien Help-Desk"),
    HTESSE_DACCUEIL("Hôtesse d'accueil"),
    HTESSE_DE_LAIR("Hôtesse de l'air"),
    HOTLINER("Hotliner"),
    HUISSIER_DE_JUSTICE("Huissier de justice"),
    ICONOGRAPHE("Iconographe"),
    INFIRMIER("Infirmier"),
    INFIRMIER_ANESTHSISTE_DIPLM_DETAT("Infirmier anesthésiste diplômé d?Etat"),
    INFIRMIER_CHEF("Infirmier chef"),
    INFIRMIER_DE_BLOC_OPRATOIRE_DIPLM_DETAT("Infirmier de bloc opératoire diplômé d?Etat"),
    INFIRMIER_DIPLM_DETAT("Infirmier diplômé d?Etat"),
    INFIRMIERE("Infirmiere"),
    INGNIEUR_AGROALIMENTAIRE("Ingénieur agroalimentaire"),
    INGNIEUR_COMMERCIAL("Ingénieur Commercial"),
    INGNIEUR_DTUDES_SANITAIRES("Ingénieur d?études sanitaires"),
    INGNIEUR_DTUDE_ET_DE_DVELOPPEMENT("Ingénieur d'étude et de développement"),
    INGNIEUR_DTUDES("Ingénieur d'études"),
    INGNIEUR_DE_CONSTRUCTION_DE_RSEAUX("Ingénieur De Construction De Réseaux"),
    INGNIEUR_DE_LABORATOIRE("Ingénieur de laboratoire"),
    INGNIEUR_DE_PRODUCTION("Ingénieur de production"),
    INGNIEUR_DE_RECHERCHE("Ingénieur de recherche"),
    INGNIEUR_DE_RECHERCHE_PRODUIT("Ingénieur de recherche produit"),
    INGNIEUR_DPLOIEMENT_DE_RSEAU("Ingénieur Déploiement De Réseau"),
    INGNIEUR_DES_SERVICES_TECHNIQUES_DU_MATRIEL("Ingénieur des services techniques du matériel"),
    INGNIEUR_DES_TRAVAUX("Ingénieur des travaux"),
    INGNIEUR_DVELOPPEMENT_DE_COMPOSANTS("Ingénieur Développement De Composants"),
    INGNIEUR_DVELOPPEMENT_LOGICIELS("Ingénieur Développement Logiciels"),
    INGNIEUR_DVELOPPEMENT_MATRIEL_LECTRONIQUE("Ingénieur Développement Matériel Électronique"),
    INGNIEUR_DU_GNIE_RURAL_DES_EAUX_ET_FORTS("ingénieur du génie rural des eaux et forêts"),
    INGNIEUR_DU_GNIE_SANITAIRE("Ingénieur du génie sanitaire"),
    INGNIEUR_DU_SON("Ingénieur du son"),
    INGNIEUR_EN_CHEF("Ingénieur en chef"),
    INGNIEUR_INTGRATION("Ingénieur Intégration"),
    INGNIEUR_LOGISTIQUE("Ingénieur logistique"),
    INGNIEUR_QUALITS_MTHODES("Ingénieur Qualités Méthodes"),
    INGNIEUR_SCURIT("Ingénieur Sécurité"),
    INGNIEUR_SUPPORT_TECHNIQUE("Ingénieur Support Technique"),
    INGNIEUR_SYSTMERSEAU("Ingénieur système-réseau"),
    INGNIEUR_SYSTMES_ET_RSEAUX("Ingénieur Systèmes Et Réseaux"),
    INGNIEUR_TECHNICOCOMMERCIAL("Ingénieur Technico-Commercial"),
    INGNIEUR_VALIDATION("Ingénieur Validation"),
    INSPECTEUR_DE_LACTION_SANITAIRE_ET_SOCIALE("Inspecteur de l'action sanitaire et sociale"),
    INSPECTEUR_DES_SYSTMES_DINFORMATION_ET_DE_COMMUNICATION("Inspecteur des systèmes d'information et de communication"),
    INSPECTEURS_DU_TRAVAIL("Inspecteurs du travail"),
    INSTALLATEUR_EN_TLCOMMUNICATIONS("Installateur en télécommunications"),
    INTGRATEUR_WEB("Intégrateur Web"),
    INTERPRTE("Interprète"),
    JEUNES_SAPEURSPOMPIERS("Jeunes sapeurs-pompiers"),
    JOURNALISTE("Journaliste"),
    JOURNALISTE_DENTREPRISE("Journaliste d'entreprise"),
    JOURNALISTE_RADIO("Journaliste radio"),
    JOURNALISTE_REPORTER("Journaliste reporter"),
    JUGE_DINSTANCE("Juge d'Instance"),
    JUGE_DINSTRUCTION("Juge d'instruction"),
    JUGE_DE_GRANDE_INSTANCE("Juge de Grande Instance"),
    JUGE_DE_LAPPLICATION_DES_PEINES("Juge de l'application des peines"),
    JUGE_DE_LEXCUTION("Juge de l'exécution"),
    JUGE_DES_AFFAIRES_FAMILIALES("Juge des affaires familiales"),
    JUGE_DES_ENFANTS("Juge des enfants"),
    JURISTE_INFORMATIQUE("Juriste Informatique"),
    LES_ADJOINTS_ADMINISTRATIFS_DE_LA_POLICE_NATIONALE("Les adjoints administratifs de la police nationale"),
    LES_ADJOINTS_DE_SCURIT("Les adjoints de sécurité"),
    LES_DIRECTEURS_DE_SERVICES_PNITENTIAIRES("Les Directeurs de services pénitentiaires"),
    LES_GREFFIERS("Les greffiers"),
    LES_PERSONNELS_DE_LA_PROTECTION_JUDICIAIRE_DE_LA_JEUNESSE("Les personnels de la protection judiciaire de la jeunesse"),
    LIBRAIRE("Libraire"),
    LIEUTENANT_DE_POLICE("Lieutenant de police"),
    LIEUTENANT_DE_SAPEURSPOMPIERS("Lieutenant de sapeurs-pompiers"),
    LIVREUR("Livreur"),
    MAON("Maçon"),
    MAGASINIER_EN_CHEF_DES_BIBLIOTHQUES("Magasinier en chef des bibliothèques"),
    MAGISTRAT("Magistrat"),
    MATRE_CHIEN("Maître chien"),
    MATRE_DHTEL("Maître d'hôtel"),
    MATRE_DE_CONFRENCE("Maître de conférence"),
    MATRE_OUVRIER_DES_TABLISSEMENTS_DENSEIGNEMENT("Maître ouvrier des établissements d'enseignement"),
    MATRENAGEUR_SAUVETEUR("Maître-nageur sauveteur"),
    MATRES_DES_TABLISSEMENTS_DENSEIGNEMENT_PRIVS_SOUS_CONTRAT("Maîtres des établissements d'enseignement privés sous contrat"),
    MAJOR_DE_SAPEURPOMPIER("Major de sapeur-pompier"),
    MANIPULATEUR_DLECTRORADIOLOGIE_MDICALE("Manipulateur d?électroradiologie médicale"),
    MANUTENTIONNAIRE_CARISTE("Manutentionnaire cariste"),
    MAQUETTISTE("Maquettiste"),
    MASSEUR_KINSITHRAPEUTE("Masseur kinésithérapeute"),
    MCANICIEN_2_ROUES("Mécanicien 2 roues"),
    MCANICIEN_AUTO("Mécanicien auto"),
    MDECIN("Médecin"),
    MDECIN_DE_LDUCATION_NATIONALE("Médecin de l'éducation nationale"),
    MDECIN_INSPECTEUR_DE_SANT_PUBLIQUE("Médecin inspecteur de santé publique"),
    MDECIN_PHARMACIEN_DE_SAPEURPOMPIER("Médecin pharmacien de Sapeur-pompier"),
    MDECIN_TERRITORIAL("Médecin Territorial"),
    MDIAPLANNER("Média-planner"),
    MDIATEUR_SOCIAL("Médiateur social"),
    MENUISIER("Menuisier"),
    MTOROLOGUE("Météorologue"),
    MTIERS_DE_LA_PRODUCTION("Métiers de la production"),
    MONITEUR_DAUTOCOLE("Moniteur d'auto-école"),
    MONITEUR_DE_SKI("Moniteur de ski"),
    MONITEUR_DUCATEUR("Moniteur éducateur"),
    MONTEUR("Monteur"),
    MONTEUR_LECTRICIEN_RSEAU_EDF("Monteur électricien réseau edf"),
    MONTEUR_EN_INSTALLATIONS_THERMIQUES_CHAUFFAGISTE("Monteur en installations thermiques chauffagiste"),
    MUSICIEN("Musicien"),
    NETSURFER("Netsurfer"),
    NOTAIRE("Notaire"),
    OCANOGRAPHE("Océanographe"),
    OPRATEUR_SUR_MACHINE_DE_PRODUCTION_LECTRIQUE("Opérateur sur machine de production électrique"),
    OPRATEUR_TERRITORIAL_DES_ACTIVITS_PHYSIQUES_ET_SPORTIVES("Opérateur territorial des activités physiques et sportives"),
    OPRATRICE_DE_SAISIE("Opératrice de saisie"),
    OPTICIEN_LUNETIER("Opticien lunetier"),
    ORTHOPHONISTE("Orthophoniste"),
    ORTHOPTISTE("Orthoptiste"),
    OUVRIER_AGRICOLE("Ouvrier agricole"),
    OUVRIER_DENTRETIEN_ET_DACCUEIL_OEA("Ouvrier d'entretien et d'accueil (OEA),"),
    OUVRIER_DTAT("Ouvrier d'État"),
    OUVRIER_PROFESSIONNEL_OP("Ouvrier professionnel (OP),"),
    OUVRIER_PROFESSIONNEL("Ouvrier professionnel"),
    PARAMTREUR_DE_PROGICIELS("Paramétreur De Progiciels"),
    PTISSIER("Pâtissier"),
    PAYSAGISTE("Paysagiste"),
    PDICURE_PODOLOGUE("Pédicure podologue"),
    PEINTRE_EN_BTIMENT("Peintre en bâtiment"),
    PPINIERISTE("Pépinieriste"),
    PERSONNEL_DE_SURVEILLANCE("Personnel de surveillance"),
    PERSONNEL_PNITENTAIRE_DINSERTION_ET_DE_PROBATION("Personnel pénitentaire d'insertion et de probation"),
    PERSONNEL_TECHNIQUE_DE_LADMINISTRATION_PNITENTIAIRE("Personnel technique de l'administration pénitentiaire"),
    PHARMACIEN("Pharmacien"),
    PHARMACIEN_INSPECTEUR_DE_SANT_PUBLIQUE("Pharmacien inspecteur de santé publique"),
    PHOTOGRAPHE("Photographe"),
    PIGISTE("Pigiste"),
    PILOTE_DAVION("Pilote d'avion"),
    PLANNEUR_STRATGIQUE("Planneur stratégique"),
    PLOMBIER("Plombier"),
    POISSONNIER("Poissonnier"),
    PRPARATEUR_EN_PHARMACIE("Préparateur en pharmacie"),
    PRPARATEUR_EN_PHARMACIE_AVEC_PUB("Préparateur en pharmacie avec Pub"),
    PROFESSEUR_AGRG("Professeur agrégé"),
    PROFESSEUR_CERTIFI("Professeur certifié"),
    PROFESSEUR_DARTS_PLASTIQUES("Professeur d'arts plastiques"),
    PROFESSEUR_DDUCATION_PHYSIQUE_ET_SPORTIVE("Professeur d'éducation physique et sportive"),
    PROFESSEUR_DUNIVERSIT("Professeur d'Université"),
    PROFESSEUR_DE_LYCE_ET_COLLGE("Professeur de lycée et collège"),
    PROFESSEUR_DE_LYCE_PROFESSIONNEL("Professeur de lycée professionnel"),
    PROFESSEUR_DE_MUSIQUE("Professeur de musique"),
    PROFESSEUR_DES_COLES("Professeur des écoles"),
    PROFESSEUR_FLE("Professeur FLE"),
    PROJECTIONNISTE("Projectionniste"),
    PROTHSISTE("Prothésiste"),
    PROTHSISTE_DENTAIRE("Prothésiste dentaire"),
    PSYCHANALYSTE("Psychanalyste"),
    PSYCHOLOGUE("Psychologue"),
    PSYCHOMOTRICIEN("Psychomotricien"),
    PURICULTRICE("Puéricultrice"),
    RALISATEUR("Réalisateur"),
    RCEPTIONNISTE("Réceptionniste"),
    RDACTEUR_CHEF("Rédacteur chef"),
    RDACTEUR_EN_ASSURANCES("Rédacteur en assurances"),
    RDACTEUR_EN_CHEF("Rédacteur en chef"),
    RDACTEUR_TECHNIQUE("Rédacteur Technique"),
    RDUCATEUR("Rééducateur"),
    RGISSEUR("Régisseur"),
    RELIEURDOREUR("Relieur-doreur"),
    RESPONSABLE_DAGENCE_BANCAIRE("Responsable d'agence bancaire"),
    RESPONSABLE_DEXPLOITATION("Responsable D'Exploitation"),
    RESPONSABLE_DUN_SYSTME_DINFORMATION_MTIER("Responsable D'Un Système D'Information Métier"),
    RESPONSABLE_DE_COMMUNICATION("Responsable de communication"),
    RESPONSABLE_DE_COMPTE("Responsable De Compte"),
    RESPONSABLE_DE_MARKETING_OPRATIONNEL("Responsable De Marketing Opérationnel"),
    RESPONSABLE_DE_SERVICE_INFORMATIQUE("Responsable De Service Informatique"),
    RESPONSABLE_DES_TUDES("Responsable Des Études"),
    RESPONSABLE_LOGISTIQUE("Responsable logistique"),
    RESPONSABLE_MARKETING("Responsable marketing"),
    RESPONSABLE_SCURIT_INFORMATIQUE("Responsable Sécurité Informatique"),
    SAGEFEMME("Sage-Femme"),
    SAPEUR_POMPIER("Sapeur pompier"),
    SAPEURPOMPIER("Sapeur-pompier"),
    SAPEURPOMPIER_VOLONTAIRE("Sapeur-Pompier Volontaire"),
    SCRIPTE("Scripte"),
    SECRTAIRE_ADMINISTRATIF("Secrétaire administratif"),
    SECRTAIRE_ADMINISTRATIF_DES_AFFAIRES_SANITAIRES_ET_SOCIALES("Secrétaire administratif des affaires sanitaires et sociales"),
    SECRTAIRE_ASSISTANTE("Secrétaire assistante"),
    SECRTAIRE_DE_MAIRIE("Secrétaire de Mairie"),
    SECRTAIRE_DE_RDACTION("Secrétaire de rédaction"),
    SECRTAIRE_JURIDIQUE("Secrétaire juridique"),
    SECRTAIRE_MDICOSOCIALE("Secrétaire médico-sociale"),
    SECRTARIAT_ADMINISTRATIF_DADMINISTRATION_CENTRALE("Secrétariat administratif d'administration centrale"),
    SCURIT_CIVILE("Sécurité civile"),
    SERVEUR_DE_RESTAURANT("Serveur de restaurant"),
    SKIPPEUR("Skippeur"),
    SOCIOLOGUE("Sociologue"),
    SOLIER_MOQUETTISTE("Solier moquettiste"),
    SOMMELIER("Sommelier"),
    SOUDEUR("Soudeur"),
    STANDARDISTE("Standardiste"),
    STENOTYPISTE("Stenotypiste"),
    STORYBOARDER("Story-boarder"),
    STYLISTE("Styliste"),
    SUPERVISEUR_DE_HOTLINE("Superviseur De Hot-Line"),
    TAXIDERMISTE("Taxidermiste"),
    TECHNICIEN("Technicien"),
    TECHNICIEN_BIOLOGISTE("Technicien biologiste"),
    TECHNICIEN_CHIMISTE("Technicien Chimiste"),
    TECHNICIEN_DE_FABRICATION("Technicien de fabrication"),
    TECHNICIEN_DE_LDUCATION_NATIONALE("Technicien de l'éducation nationale"),
    TECHNICIEN_DE_LINTERVENTION_SOCIALE_ET_FAMILIALE("Technicien de l'intervention sociale et familiale"),
    TECHNICIEN_DE_LABO_PHOTO("Technicien de labo photo"),
    TECHNICIEN_DE_LABORATOIRE("Technicien de laboratoire"),
    TECHNICIEN_EN_ANALYSES_BIOMDICALES("Technicien en analyses biomédicales"),
    TECHNICIEN_EN_MCANIQUE("Technicien en mécanique"),
    TECHNICIEN_FORESTIER("Technicien forestier"),
    TECHNICIEN_LIGNE_HAUTE_TENSION("Technicien ligne haute tension"),
    TECHNICIEN_MAINTENANCE_AUTO("Technicien maintenance auto"),
    TECHNICIEN_MICRO("Technicien Micro"),
    TECHNICIEN_RSEAU("Technicien Réseau"),
    TECHNICIEN_TRAITEMENT_DCHETS("Technicien traitement déchets"),
    TECHNICIENS_DE_RECHERCHE_ET_DE_FORMATION("Techniciens de recherche et de formation"),
    TLVENDEUR("Télévendeur"),
    TOILETTEUR("Toiletteur"),
    TLIER("Tôlier"),
    TOURNEURFRAISEUR("Tourneur-fraiseur"),
    TRADER("Trader"),
    TRADUCTEUR("Traducteur"),
    TRAFFIC_MANAGER("Traffic Manager"),
    URBANISTE("Urbaniste"),
    VENDEUR_EN_MAGASIN("Vendeur en magasin"),
    VENDEUR_EN_MICROINFORMATIQUE("Vendeur En Micro-Informatique"),
    VERRIER("Verrier"),
    VTRINAIRE("Vétérinaire"),
    VITICULTEUR("Viticulteur"),
    VRP("VRP"),
    WEBDESIGNER("Webdesigner"),
    WEBMARKETEUR("Webmarketeur"),
    WEBMASTER("Webmaster"),
    WEBMESTRE("Webmestre"),
    WEBPLANNER("Webplanner"),
    CULTURE_ET_PRODUCTION_ANIMALE_CHASSE_ET_SERVICES_ANNEXES("Culture et production animale, chasse et services annexes"),
    SYLVICULTURE_ET_EXPLOITATION_FORESTIRE("Sylviculture et exploitation forestière"),
    PCHE_ET_AQUACULTURE("Pêche et aquaculture"),
    EXTRACTION_DE_HOUILLE_ET_DE_LIGNITE("Extraction de houille et de lignite"),
    EXTRACTION_DHYDROCARBURES("Extraction d'hydrocarbures"),
    EXTRACTION_DE_MINERAIS_MTALLIQUES("Extraction de minerais métalliques"),
    AUTRES_INDUSTRIES_EXTRACTIVES("Autres industries extractives"),
    SERVICES_DE_SOUTIEN_AUX_INDUSTRIES_EXTRACTIVES("Services de soutien aux industries extractives"),
    INDUSTRIES_ALIMENTAIRES("Industries alimentaires"),
    FABRICATION_DE_BOISSONS("Fabrication de boissons"),
    FABRICATION_DE_PRODUITS_BASE_DE_TABAC("Fabrication de produits à base de tabac"),
    FABRICATION_DE_TEXTILES("Fabrication de textiles"),
    INDUSTRIE_DE_LHABILLEMENT("Industrie de l'habillement"),
    INDUSTRIE_DU_CUIR_ET_DE_LA_CHAUSSURE("Industrie du cuir et de la chaussure"),
    TRAVAIL_DU_BOIS_ET_FABRICATION_DARTICLES_EN_BOIS("Travail du bois et fabrication d'articles en bois"),
    INDUSTRIE_DU_PAPIER_ET_DU_CARTON("Industrie du papier et du carton"),
    IMPRIMERIE_ET_REPRODUCTION_DENREGISTREMENTS("Imprimerie et reproduction d'enregistrements"),
    COKFACTION_ET_RAFFINAGE("Cokéfaction et raffinage"),
    INDUSTRIE_CHIMIQUE("Industrie chimique"),
    INDUSTRIE_PHARMACEUTIQUE("Industrie pharmaceutique"),
    FABRICATION_DE_PRODUITS_EN_CAOUTCHOUC_ET_EN_PLASTIQUE("Fabrication de produits en caoutchouc et en plastique"),
    FABRICATION_DAUTRES_PRODUITS_MINRAUX_NON_MTALLIQUES("Fabrication d'autres produits minéraux non métalliques"),
    MTALLURGIE("Métallurgie"),
    FABRICATION_DE_PRODUITS_MTALLIQUES("Fabrication de produits métalliques"),
    FABRICATION_DE_PRODUITS_INFORMATIQUES_LECTRONIQUES_ET_OPTIQUES("Fabrication de produits informatiques, électroniques et optiques"),
    FABRICATION_DQUIPEMENTS_LECTRIQUES("Fabrication d'équipements électriques"),
    FABRICATION_DE_MACHINES_ET_QUIPEMENTS_NCA("Fabrication de machines et équipements n.c.a."),
    INDUSTRIE_AUTOMOBILE("Industrie automobile"),
    FABRICATION_DAUTRES_MATRIELS_DE_TRANSPORT("Fabrication d'autres matériels de transport"),
    FABRICATION_DE_MEUBLES("Fabrication de meubles"),
    AUTRES_INDUSTRIES_MANUFACTURIRES("Autres industries manufacturières"),
    RPARATION_ET_INSTALLATION_DE_MACHINES_ET_DQUIPEMENTS("Réparation et installation de machines et d|équipements"),
    PRODUCTION_ET_DISTRIBUTION_DLECTRICIT_DE_GAZ("Production et distribution d'électricité, de gaz"),
    CAPTAGE_TRAITEMENT_ET_DISTRIBUTION_DEAU("Captage, traitement et distribution d'eau"),
    COLLECTE_ET_TRAITEMENT_DES_EAUX_USES("Collecte et traitement des eaux usées"),
    COLLECTE_TRAITEMENT_ET_LIMINATION_DES_DCHETS_RCUPRATION("Collecte, traitement et élimination des déchets, récupération"),
    DPOLLUTION_ET_AUTRES_SERVICES_DE_GESTION_DES_DCHETS("Dépollution et autres services de gestion des déchets"),
    CONSTRUCTION_DE_BTIMENTS("Construction de bâtiments"),
    GNIE_CIVIL("Génie civil"),
    TRAVAUX_DE_CONSTRUCTION_SPCIALISS("Travaux de construction spécialisés"),
    COMMERCE_ET_RPARATION_DAUTOMOBILES_ET_DE_MOTOCYCLES("Commerce et réparation d'automobiles et de motocycles"),
    COMMERCE_DE_GROS("Commerce de gros"),
    COMMERCE_DE_DTAIL("Commerce de détail"),
    TRANSPORTS_TERRESTRES_ET_TRANSPORT_PAR_CONDUITES("Transports terrestres et transport par conduites"),
    TRANSPORTS_PAR_EAU("Transports par eau"),
    TRANSPORTS_ARIENS("Transports aériens"),
    ENTREPOSAGE_ET_SERVICES_AUXILIAIRES_DES_TRANSPORTS("Entreposage et services auxiliaires des transports"),
    ACTIVITS_DE_POSTE_ET_DE_COURRIER("Activités de poste et de courrier"),
    HBERGEMENT("Hébergement"),
    RESTAURATION("Restauration"),
    DITION("Édition"),
    PRODUCTION_DE_FILMS_CINMATOGRAPHIQUES_ET_DE_VIDO("Production de films cinématographiques et de vidéo"),
    PROGRAMMATION_ET_DIFFUSION("Programmation et diffusion"),
    TLCOMMUNICATIONS("Télécommunications"),
    PROGRAMMATION_CONSEIL_ET_AUTRES_ACTIVITS_INFORMATIQUES("Programmation, conseil et autres activités informatiques"),
    SERVICES_DINFORMATION("Services d'information"),
    ACTIVITS_DES_SERVICES_FINANCIERS("Activités des services financiers"),
    ASSURANCE("Assurance"),
    ACTIVITS_AUXILIAIRES_DE_SERVICES_FINANCIERS_ET_DASSURANCE("Activités auxiliaires de services financiers et d'assurance"),
    ACTIVITS_IMMOBILIRES("Activités immobilières"),
    ACTIVITS_JURIDIQUES_ET_COMPTABLES("Activités juridiques et comptables"),
    ACTIVITS_DES_SIGES_SOCIAUX_CONSEIL_DE_GESTION("Activités des sièges sociaux ; conseil de gestion"),
    ACTIVITS_DARCHITECTURE_ET_DINGNIERIE("Activités d'architecture et d'ingénierie"),
    ACTIVITS_DE_CONTRLE_ET_ANALYSES_TECHNIQUES("Activités de contrôle et analyses techniques"),
    RECHERCHEDVELOPPEMENT_SCIENTIFIQUE("Recherche-développement scientifique"),
    PUBLICIT_ET_TUDES_DE_MARCH("Publicité et études de marché"),
    AUTRES_ACTIVITS_SPCIALISES_SCIENTIFIQUES_ET_TECHNIQUES("Autres activités spécialisées, scientifiques et techniques"),
    ACTIVITS_VTRINAIRES("Activités vétérinaires"),
    ACTIVITS_DE_LOCATION_ET_LOCATIONBAIL("Activités de location et location-bail"),
    ACTIVITS_LIES_LEMPLOI("Activités liées à l'emploi"),
    ACTIVITS_DES_AGENCES_DE_VOYAGE_ET_ACTIVITS_CONNEXES("Activités des agences de voyage et activités connexes"),
    ENQUTES_ET_SCURIT("Enquêtes et sécurité"),
    SERVICES_RELATIFS_AUX_BTIMENTS_ET_AMNAGEMENT_PAYSAGER("Services relatifs aux bâtiments et aménagement paysager"),
    ACTIVITS_ADMINISTRATIVES("Activités administratives"),
    ADMINISTRATION_PUBLIQUE_ET_DFENSE("Administration publique et défense"),
    ENSEIGNEMENT("Enseignement"),
    ACTIVITS_POUR_LA_SANT_HUMAINE("Activités pour la santé humaine"),
    HBERGEMENT_MDICOSOCIAL_ET_SOCIAL("Hébergement médico-social et social"),
    ACTION_SOCIALE_SANS_HBERGEMENT("Action sociale sans hébergement"),
    ACTIVITS_CRATIVES_ARTISTIQUES_ET_DE_SPECTACLE("Activités créatives, artistiques et de spectacle"),
    BIBLIOTHQUES_ARCHIVES_MUSES("Bibliothèques, archives, musées"),
    ORGANISATION_DE_JEUX_DE_HASARD_ET_DARGENT("Organisation de jeux de hasard et d'argent"),
    ACTIVITS_SPORTIVES_RCRATIVES_ET_DE_LOISIRS("Activités sportives, récréatives et de loisirs"),
    ACTIVITS_DES_ORGANISATIONS_ASSOCIATIVES("Activités des organisations associatives"),
    RPARATION_DE_BIENS_PERSONNELS_ET_DOMESTIQUES("Réparation de biens personnels et domestiques"),
    AUTRES_SERVICES_PERSONNELS("Autres services personnels"),
    ACTIVITS_DES_MNAGES("Activités des ménages"),
    ACTIVITS_INDIFFRENCIES_DES_MNAGES("Activités indifférenciées des ménages"),
    ACTIVITS_DES_ORGANISATIONS_ET_ORGANISMES_EXTRATERRITORIAUX("Activités des organisations et organismes extraterritoriaux")
;

    private final String description;

    ProfessionEnum(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }
}